name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    strategy:
      matrix:
        nvim-versions: ['stable', 'nightly']
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: source-files-filter
        with:
          filters: |
            source-files:
              - 'lua/**'
              - 'plugin/**'
              - 'tests/**'

      - uses: jitterbit/get-changed-files@v1
        id: source-files
        with:
          # Format of the steps output context.
          # Can be 'space-delimited', 'csv', or 'json'.
          # Default: 'space-delimited'
          format: 'space-delimited'

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: run tests
        if: steps.source-files-filter.outputs.source-files == 'true'
        run: make test
